### ISSUE TITLE
Could this be used as a backend for rustc's new `x86_64-unknown-linux-none` target?

### ISSUE THREAD

**Issue by tbu-** [sunfishcode/origin#118]
CC https://github.com/rust-lang/rust/pull/125023

I see that this crate implements threads and an allocator, this sounds like a good base for an `std` library for x86_64-unknown-linux-none.

**Comment by sunfishcode** [comment]
Yes, it could. For example, [Eyra](https://github.com/sunfishcode/eyra) demonstrates that origin is complete enough to handle program and thread startup and shutdown for complete Rust programs.

**Comment by tbu-** [comment]
Thanks for the answer. I somehow overlooked it. :)
