### ISSUE TITLE
Race condition in munmap_and_exit_thread with signal handlers

### ISSUE THREAD

**Issue by bjorn3** [sunfishcode/origin#125]
It is possible for a signal handler to run between unmapping the stack and exiting. When this happens either the signal handler crashes, or if an other thread happened to create a new mapping at the original location of the stack you will get memory corruption.

Musl has the same race condition and it isn't all that likely to be hit I think and it is likely pretty hard to fix.

**Comment by sunfishcode** [comment]
We can fix this by using `rt_sigprocmask` to block signals before we free the stack. I filed #126 to implement this; see the description for a more detailed description.

At a quick glance, it looks like Musl does this as well.
