### ISSUE TITLE
Could origin work without an allocator?

### ISSUE THREAD

**Issue by morr0ne** [sunfishcode/origin#15]
As the title says, would it be possible to have a subset of the library work without allocations? I was messing around with the origin-start example and the it seems like the most minimal working code I could manage is this:
```rust 
#![no_std]
#![no_main]
#![allow(internal_features)]
#![feature(lang_items)]
#![feature(core_intrinsics)]

use origin::*;

#[panic_handler]
fn panic(panic: &core::panic::PanicInfo<'_>) -> ! {
    core::intrinsics::abort();
}

#[lang = "eh_personality"]
extern "C" fn eh_personality() {}

#[global_allocator]
static GLOBAL_ALLOCATOR: rustix_dlmalloc::GlobalDlmalloc = rustix_dlmalloc::GlobalDlmalloc;

#[no_mangle]
extern "C" fn main(_argc: i32, _argv: *const *const u8) -> i32 {
    exit(0);
}
```
Unfortunately removing the allocator gives me a compiler error stating that an allocator is necessary. I am wondering is it possible to have the program startup and shutdown implemented without allocations? I don't need threading or at least I don't think I do. Unless threading is actually necessary even for a single threaded program?

**Comment by morr0ne** [comment]
Just to be clear, I did try not enabling the origin-threads feature but doing so yields a bunch of compiler errors about the libc crate missing

**Comment by morr0ne** [comment]
Okay so looking into the library I see that thread creation is necessary regardless of multi threading or not but seems to be fundamental in the startup code. The question still remains however, could it exists a version that does not require an allocator even if much more limited in scope?

**Comment by sunfishcode** [comment]
Yeah, I expect it should be possible to make origin do that. If we introduce an "alloc" feature and put things like `at_exit` and threads and related code behind `cfg(feature = "alloc")`, I'd guess that'd work.

**Comment by sunfishcode** [comment]
There's also rustix, which origin depends on, and which uses an allocator for some things. But, I imagine it could also add an "alloc" feature and put things that require alloc behind `cfg(feature = "alloc")`.
