### ISSUE TITLE
Refactor code organization for different implementations

### ISSUE THREAD

**Issue by morr0ne** [sunfishcode/origin#18]
Currently the project is using prefix in the name and `path` cfg directives to switch between different implementation depending on the arch and wheter or not libc is used. This can get somewhat confusing and it doesn't allow for proper separation of code. I think a better solution is to properly separate the various implementations.

Instead of the following tree structure:
<pre>
src
├── arch-aarch64.rs
├── arch-arm.rs
├── arch-riscv64.rs
├── arch-x86.rs
├── arch-x86_64.rs
├── lib.rs
├── program.rs
├── signals.rs
├── signals_via_libc.rs
├── threads.rs
├── threads_via_pthreads.rs
└── unwind.rs
</pre>

I propose organizing the code the following way:
<pre>
src
├── arch
│   ├── aarch64.rs
│   ├── arch-x86.rs
│   ├── arm.rs
│   ├── riscv64.rs
│   └── x86_64.rs
├── arch.rs
├── lib.rs
├── program.rs
├── signals
│   ├── libc.rs
│   └── raw.rs
├── signals.rs
├── threads
│   ├── libc.rs
│   └── raw.rs
├── threads.rs
└── unwind.rs
</pre>

Or peraphs another solution is to organize similar to how rustix does it:
<pre>
src
├── arch
│   ├── aarch64.rs
│   ├── arch-x86.rs
│   ├── arm.rs
│   ├── riscv64.rs
│   └── x86_64.rs
├── arch.rs
├── backend
│   ├── libc
│   │   ├── signals
│   │   │   └── mod.rs
│   │   └── threads
│   │       └── mod.rs
│   └── linux_raw
│       ├── signals
│       │   └── mod.rs
│       └── threads
│           └── mod.rs
├── lib.rs
├── program.rs
├── threads
└── unwind.rs
</pre>

This latter option however, might be a bit overkill considering the much smaller codebase of origin

Both cases would allow for better code separation and organization, make it easier to add support for other architectures and/or features, and would also make it easier to add a more granular control over features

**Comment by sunfishcode** [comment]
Good idea. I filed #19 implementing your first proposal.
