### ISSUE TITLE
Add a changelog/releases file

### ISSUE THREAD

**Issue by morr0ne** [sunfishcode/origin#31]
I think it would greatly benefit the project to add a file that keep tracks of changes and/or releases. I think the benefits are obvious but the most notable reason right now is making it clearer what changes between breaking release. I don't think it would make sense to include very old released but 0.12.0 seems like a good starting point considering it was a breaking release and it's the latest one. Ideally this could also be coordinated with github releases, I am not sure what the best tool to keep those 2 things in sync would be but ideally there could be some kind of ci job that handles releases. Perhaps it would make sense to integrate this with something like [conventional commits](https://www.conventionalcommits.org/) to allow for easy changelog generation without requiring manual intervention. That would also require some kind of contributing guidelines to enforce it but I reckon contributing guidelines are always a good idea.

**Comment by sunfishcode** [comment]
Yes, this is a good idea. I'm not a fan of conventionalcommits' syntax, but I will try to keep track of breaking changes and add notes to the releases.

**Comment by sunfishcode** [comment]
I just released 0.13.0, and added release notes [here](https://github.com/sunfishcode/origin/releases/tag/v0.13.0).

**Comment by morr0ne** [comment]
I feel like release notes should always be included in the repo. What happens if the project is not hosted on github anymore? Or forked? Or if someone wants to check changes from a local copy or mirror? Github releases are great but they should definitely co-exist with a `CHANGELOG.md` file of sorts

**Comment by sunfishcode** [comment]
Starting with the 0.14 release, I've now added a CHANGELOG.md file.
